In [28]:
import numpy as np
import pandas as pd
import matplotlib
import csv

In [29]:
database = pd.read_csv("CourseRetSuccessSumm.csv")

In [38]:
# So far cleaned first two columns and brainstorming most efficient way to clean the data 
listedout = database['Unnamed: 2'] == 'Nan'
# database['Unnamed: 4'] = database['Unnamed: 4'] == 'African-American'
start_cleaning = database.drop(['Unnamed: 0', 'Unnamed: 1'], axis=1)
start_cleaning.iloc[:,:29]

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Fall 2010,Fall 2010.1,Fall 2010.2,Fall 2010.3,Fall 2010.4,Fall 2010.5,Fall 2010.6,...,Fall 2010.16,Fall 2010.17,Fall 2010.18,Fall 2010.19,Fall 2010.20,Fall 2010.21,Fall 2010.22,Fall 2010.23,Fall 2010.24,Fall 2011
0,NaN,NaN,NaN,Basic Skills,Basic Skills,Basic Skills,Basic Skills,Basic Skills,Credit,Credit,...,Transferable,Transferable,Transferable,Transferable,Vocational,Vocational,Vocational,Vocational,Vocational,Basic Skills
1,Gender,Age Group,Ethnicity,Enrollment Count,Retention Count,Success Count,Retention Rate,Success Rate,Enrollment Count,Retention Count,...,Retention Count,Success Count,Retention Rate,Success Rate,Enrollment Count,Retention Count,Success Count,Retention Rate,Success Rate,Enrollment Count
2,Female,1 to 17,African-American,427,364,251,85.25 %,58.78 %,"4,189","3,695",...,"2,849","2,220",88.70 %,69.12 %,751,655,495,87.22 %,65.91 %,364
3,Female,1 to 17,American Indian/Alaskan Native,26,23,15,88.46 %,57.69 %,294,262,...,208,174,89.27 %,74.68 %,29,27,23,93.10 %,79.31 %,32
4,Female,1 to 17,Asian,693,644,560,92.93 %,80.81 %,"9,514","8,862",...,"7,040","6,397",92.96 %,84.47 %,"1,199","1,108",999,92.41 %,83.32 %,563
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,Unknown,Unknown,Asian,2,2,2,100.00 %,100.00 %,11,10,...,5,2,83.33 %,33.33 %,4,4,3,100.00 %,75.00 %,NaN
265,Unknown,Unknown,Hispanic,2,2,0,100.00 %,0.00 %,18,18,...,11,7,100.00 %,63.64 %,10,10,8,100.00 %,80.00 %,1
266,Unknown,Unknown,Pacific Islander,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,Unknown,Unknown,Unknown,5,4,2,80.00 %,40.00 %,48,46,...,32,29,96.97 %,87.88 %,21,20,20,95.24 %,95.24 %,4
268,Unknown,Unknown,White Non-Hispanic,NaN,NaN,NaN,NaN,NaN,4,3,...,1,1,50.00 %,50.00 %,2,2,2,100.00 %,100.00 %,NaN

In [31]:
# age_range = start_cleaning['Unnamed: 3'].unique()
# listed = start_cleaning['Unnamed: 3'] == ('20 to 24' or 'Age Group')
# age_range

In [32]:
start_cleaning[listed]
start_cleaning= start_cleaning.rename(columns={'Unnamed: 2': 'Gender', 'Unnamed: 3': 'Age Group', 'Unnamed: 4': 'Ethnicity'})
start_cleaning.head(15)

,Gender,Age Group,Ethnicity,Fall 2010,Fall 2010.1,Fall 2010.2,Fall 2010.3,Fall 2010.4,Fall 2010.5,Fall 2010.6,...,Winter 2020.15,Winter 2020.16,Winter 2020.17,Winter 2020.18,Winter 2020.19,Winter 2020.20,Winter 2020.21,Winter 2020.22,Winter 2020.23,Winter 2020.24
0,NaN,NaN,NaN,Basic Skills,Basic Skills,Basic Skills,Basic Skills,Basic Skills,Credit,Credit,...,Transferable,Transferable,Transferable,Transferable,Transferable,Vocational,Vocational,Vocational,Vocational,Vocational
1,Gender,Age Group,Ethnicity,Enrollment Count,Retention Count,Success Count,Retention Rate,Success Rate,Enrollment Count,Retention Count,...,Enrollment Count,Retention Count,Success Count,Retention Rate,Success Rate,Enrollment Count,Retention Count,Success Count,Retention Rate,Success Rate
2,Female,1 to 17,African-American,427,364,251,85.25 %,58.78 %,"4,189","3,695",...,100,97,90,97.00 %,90.00 %,13,13,13,100.00 %,100.00 %
3,Female,1 to 17,American Indian/Alaskan Native,26,23,15,88.46 %,57.69 %,294,262,...,6,6,5,100.00 %,83.33 %,2,2,1,100.00 %,50.00 %
4,Female,1 to 17,Asian,693,644,560,92.93 %,80.81 %,"9,514","8,862",...,627,612,590,97.61 %,94.10 %,130,127,119,97.69 %,91.54 %
5,Female,1 to 17,Hispanic,"3,067","2,807","2,116",91.52 %,68.99 %,"27,370","24,792",...,"1,123","1,073",949,95.55 %,84.51 %,241,238,202,98.76 %,83.82 %
6,Female,1 to 17,Multi-Ethnicity,151,133,103,88.08 %,68.21 %,"2,576","2,324",...,149,142,130,95.30 %,87.25 %,34,34,32,100.00 %,94.12 %
7,Female,1 to 17,Pacific Islander,31,28,19,90.32 %,61.29 %,366,334,...,6,6,5,100.00 %,83.33 %,3,3,2,100.00 %,66.67 %
8,Female,1 to 17,Unknown,265,244,204,92.08 %,76.98 %,"4,099","3,721",...,154,153,142,99.35 %,92.21 %,23,23,21,100.00 %,91.30 %
9,Female,1 to 17,White Non-Hispanic,"1,009",897,732,88.90 %,72.55 %,"21,321","19,537",...,717,699,658,97.49 %,91.77 %,217,214,199,98.62 %,91.71 %
10,Female,18 & 19,African-American,"5,189","4,206","2,705",81.06 %,52.13 %,"32,644","26,631",...,"1,055",961,794,91.09 %,75.26 %,99,90,73,90.91 %,73.74 %
11,Female,18 & 19,American Indian/Alaskan Native,239,201,144,84.10 %,60.25 %,"2,534","2,182",...,31,30,26,96.77 %,83.87 %,3,3,3,100.00 %,100.00 %
12,Female,18 & 19,Asian,"6,783","6,205","5,132",91.48 %,75.66 %,"71,510","63,831",...,"5,308","5,037","4,788",94.89 %,90.20 %,571,546,526,95.62 %,92.12 %
13,Female,18 & 19,Hispanic,"35,551","31,223","22,635",87.83 %,63.67 %,"256,367","222,257",...,"14,176","13,138","11,387",92.68 %,80.33 %,"1,432","1,318","1,159",92.04 %,80.94 %
14,Female,18 & 19,Multi-Ethnicity,"1,678","1,459","1,082",86.95 %,64.48 %,"21,991","18,973",...,903,844,758,93.47 %,83.94 %,83,78,71,93.98 %,85.54 %

In [34]:
def clean_fall2010_data(database):
    database=database.iloc[:,:29]
    gender_array = database['Gender']
    Age_group = database['Age Group']
    ethnicity = database['Ethnicity']
    basic_enrollment = database['Fall 2010']
    basic_retention = database['Fall 2010.1']
    basic_success = database['Fall 2010.2']
    basic_retrate = database['Fall 2010.3']
    basic_succrate = database['Fall 2010.4']
    combined = {'Gender':gender_array, 'Age Group':Age_group, 'Ethnicity':ethnicity, 'Enrollment Count':basic_enrollment,
               'Retention Count':basic_retention, 'Success Count':basic_success, 'Retention Rate':basic_retrate, 'Success Rate':basic_succrate}
    fall2010 = pd.DataFrame(data=combined)
    fall2010 = fall2010.drop([0,1])
    return fall2010

clean_fall2010_data(start_cleaning)

,Gender,Age Group,Ethnicity,Enrollment Count,Retention Count,Success Count,Retention Rate,Success Rate
2,Female,1 to 17,African-American,427,364,251,85.25 %,58.78 %
3,Female,1 to 17,American Indian/Alaskan Native,26,23,15,88.46 %,57.69 %
4,Female,1 to 17,Asian,693,644,560,92.93 %,80.81 %
5,Female,1 to 17,Hispanic,"3,067","2,807","2,116",91.52 %,68.99 %
6,Female,1 to 17,Multi-Ethnicity,151,133,103,88.08 %,68.21 %
...,...,...,...,...,...,...,...,...
264,Unknown,Unknown,Asian,2,2,2,100.00 %,100.00 %
265,Unknown,Unknown,Hispanic,2,2,0,100.00 %,0.00 %
266,Unknown,Unknown,Pacific Islander,NaN,NaN,NaN,NaN,NaN
267,Unknown,Unknown,Unknown,5,4,2,80.00 %,40.00 %
268,Unknown,Unknown,White Non-Hispanic,NaN,NaN,NaN,NaN,NaN

In [35]:
start_cleaning.transpose()

,0,1,2,3,4,5,6,7,8,9,...,259,260,261,262,263,264,265,266,267,268
Gender,NaN,Gender,Female,Female,Female,Female,Female,Female,Female,Female,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
Age Group,NaN,Age Group,1 to 17,1 to 17,1 to 17,1 to 17,1 to 17,1 to 17,1 to 17,1 to 17,...,50 +,50 +,50 +,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
Ethnicity,NaN,Ethnicity,African-American,American Indian/Alaskan Native,Asian,Hispanic,Multi-Ethnicity,Pacific Islander,Unknown,White Non-Hispanic,...,Pacific Islander,Unknown,White Non-Hispanic,African-American,American Indian/Alaskan Native,Asian,Hispanic,Pacific Islander,Unknown,White Non-Hispanic
Fall 2010,Basic Skills,Enrollment Count,427,26,693,"3,067",151,31,265,"1,009",...,2,51,52,NaN,NaN,2,2,NaN,5,NaN
Fall 2010.1,Basic Skills,Retention Count,364,23,644,"2,807",133,28,244,897,...,2,41,48,NaN,NaN,2,2,NaN,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Winter 2020.20,Vocational,Enrollment Count,13,2,130,241,34,3,23,217,...,NaN,8,4,NaN,NaN,NaN,1,NaN,NaN,NaN
Winter 2020.21,Vocational,Retention Count,13,2,127,238,34,3,23,214,...,NaN,8,3,NaN,NaN,NaN,1,NaN,NaN,NaN
Winter 2020.22,Vocational,Success Count,13,1,119,202,32,2,21,199,...,NaN,7,3,NaN,NaN,NaN,1,NaN,NaN,NaN
Winter 2020.23,Vocational,Retention Rate,100.00 %,100.00 %,97.69 %,98.76 %,100.00 %,100.00 %,100.00 %,98.62 %,...,NaN,100.00 %,75.00 %,NaN,NaN,NaN,100.00 %,NaN,NaN,NaN
Winter 2020.24,Vocational,Success Rate,100.00 %,50.00 %,91.54 %,83.82 %,94.12 %,66.67 %,91.30 %,91.71 %,...,NaN,87.50 %,75.00 %,NaN,NaN,NaN,100.00 %,NaN,NaN,NaN