In [2]:
import numpy as np
import pandas as pd
import matplotlib
import csv

In [9]:
database = pd.read_csv("CourseRetSuccessSumm.csv")

In [50]:
# So far cleaned first two columns and brainstorming most efficient way to clean the data 
listedout = database['Unnamed: 2'] == 'Nan'
# database['Unnamed: 4'] = database['Unnamed: 4'] == 'African-American'
start_cleaning = database.drop(['Unnamed: 0', 'Unnamed: 1'], axis=1)
start_cleaning.iloc[:10,:30]

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Fall 2010,Fall 2010.1,Fall 2010.2,Fall 2010.3,Fall 2010.4,Fall 2010.5,Fall 2010.6,...,Fall 2010.17,Fall 2010.18,Fall 2010.19,Fall 2010.20,Fall 2010.21,Fall 2010.22,Fall 2010.23,Fall 2010.24,Fall 2011,Fall 2011.1
0,NaN,NaN,NaN,Basic Skills,Basic Skills,Basic Skills,Basic Skills,Basic Skills,Credit,Credit,...,Transferable,Transferable,Transferable,Vocational,Vocational,Vocational,Vocational,Vocational,Basic Skills,Basic Skills
1,Gender,Age Group,Ethnicity,Enrollment Count,Retention Count,Success Count,Retention Rate,Success Rate,Enrollment Count,Retention Count,...,Success Count,Retention Rate,Success Rate,Enrollment Count,Retention Count,Success Count,Retention Rate,Success Rate,Enrollment Count,Retention Count
2,Female,1 to 17,African-American,427,364,251,85.25 %,58.78 %,"4,189","3,695",...,"2,220",88.70 %,69.12 %,751,655,495,87.22 %,65.91 %,364,321
3,Female,1 to 17,American Indian/Alaskan Native,26,23,15,88.46 %,57.69 %,294,262,...,174,89.27 %,74.68 %,29,27,23,93.10 %,79.31 %,32,28
4,Female,1 to 17,Asian,693,644,560,92.93 %,80.81 %,"9,514","8,862",...,"6,397",92.96 %,84.47 %,"1,199","1,108",999,92.41 %,83.32 %,563,528
5,Female,1 to 17,Hispanic,"3,067","2,807","2,116",91.52 %,68.99 %,"27,370","24,792",...,"14,975",90.46 %,72.88 %,"4,495","4,112","3,281",91.48 %,72.99 %,"2,746","2,540"
6,Female,1 to 17,Multi-Ethnicity,151,133,103,88.08 %,68.21 %,"2,576","2,324",...,"1,652",90.43 %,77.12 %,353,310,246,87.82 %,69.69 %,167,147
7,Female,1 to 17,Pacific Islander,31,28,19,90.32 %,61.29 %,366,334,...,213,92.07 %,73.45 %,58,54,36,93.10 %,62.07 %,34,26
8,Female,1 to 17,Unknown,265,244,204,92.08 %,76.98 %,"4,099","3,721",...,"2,680",90.39 %,79.98 %,673,604,509,89.75 %,75.63 %,145,133
9,Female,1 to 17,White Non-Hispanic,"1,009",897,732,88.90 %,72.55 %,"21,321","19,537",...,"14,729",91.72 %,81.95 %,"3,025","2,762","2,403",91.31 %,79.44 %,808,742

In [55]:
age_range = start_cleaning['Unnamed: 3'].unique()
listed = start_cleaning['Unnamed: 3'] == ('20 to 24' or 'Age Group')
# age_range
start_cleaning[listed].iloc[:10,:20]

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Fall 2010,Fall 2010.1,Fall 2010.2,Fall 2010.3,Fall 2010.4,Fall 2010.5,Fall 2010.6,Fall 2010.7,Fall 2010.8,Fall 2010.9,Fall 2010.10,Fall 2010.11,Fall 2010.12,Fall 2010.13,Fall 2010.14,Fall 2010.15,Fall 2010.16
18,Female,20 to 24,African-American,"5,439","4,128","2,500",75.90 %,45.96 %,"48,981","37,662","25,997",76.89 %,53.08 %,"42,993","33,095","23,171",76.98 %,53.89 %,"37,679","29,089"
19,Female,20 to 24,American Indian/Alaskan Native,233,197,131,84.55 %,56.22 %,"4,182","3,451","2,660",82.52 %,63.61 %,"3,915","3,225","2,505",82.38 %,63.98 %,"3,453","2,853"
20,Female,20 to 24,Asian,"6,391","5,637","4,678",88.20 %,73.20 %,"103,145","88,607","76,006",85.91 %,73.69 %,"95,860","82,211","70,673",85.76 %,73.73 %,"88,197","75,635"
21,Female,20 to 24,Hispanic,"20,858","17,115","11,884",82.05 %,56.98 %,"260,471","214,657","165,271",82.41 %,63.45 %,"237,426","195,679","151,875",82.42 %,63.97 %,"210,967","174,372"
22,Female,20 to 24,Multi-Ethnicity,799,641,459,80.23 %,57.45 %,"13,369","10,788","8,460",80.69 %,63.28 %,"12,474","10,068","7,934",80.71 %,63.60 %,"11,294","9,123"
23,Female,20 to 24,Pacific Islander,281,223,154,79.36 %,54.80 %,"4,642","3,711","2,851",79.94 %,61.42 %,"4,326","3,459","2,673",79.96 %,61.79 %,"3,913","3,126"
24,Female,20 to 24,Unknown,"2,714","2,260","1,675",83.27 %,61.72 %,"45,456","38,200","31,540",84.04 %,69.39 %,"42,304","35,561","29,564",84.06 %,69.88 %,"37,973","31,938"
25,Female,20 to 24,White Non-Hispanic,"7,664","6,442","4,938",84.06 %,64.43 %,"192,899","163,863","139,279",84.95 %,72.20 %,"183,903","156,234","133,329",84.95 %,72.50 %,"165,689","140,853"
90,Male,20 to 24,African-American,"3,937","2,880","1,589",73.15 %,40.36 %,"46,558","36,829","24,881",79.10 %,53.44 %,"42,205","33,614","23,092",79.64 %,54.71 %,"37,540","30,082"
91,Male,20 to 24,American Indian/Alaskan Native,172,142,81,82.56 %,47.09 %,"3,780","3,132","2,388",82.86 %,63.17 %,"3,568","2,959","2,282",82.93 %,63.96 %,"3,126","2,582"

In [ ]:
def clean_ethnicity_data(database):
    for i in database['Unnamed: 4']:
        if i == 'African-American':

In [ ]:
target_data = pd.database()