In [2]:
import numpy as np
import pandas as pd
import matplotlib
import csv

In [3]:
database = pd.read_csv("CourseRetSuccessSumm.csv")

In [4]:
# So far cleaned first two columns and brainstorming most efficient way to clean the data 
listedout = database['Unnamed: 2'] == 'Nan'
# database['Unnamed: 4'] = database['Unnamed: 4'] == 'African-American'
start_cleaning = database.drop(['Unnamed: 0', 'Unnamed: 1'], axis=1)
start_cleaning.iloc[:,:29]

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Fall 2010,Fall 2010.1,Fall 2010.2,Fall 2010.3,Fall 2010.4,Fall 2010.5,Fall 2010.6,...,Fall 2010.16,Fall 2010.17,Fall 2010.18,Fall 2010.19,Fall 2010.20,Fall 2010.21,Fall 2010.22,Fall 2010.23,Fall 2010.24,Fall 2011
0,NaN,NaN,NaN,Basic Skills,Basic Skills,Basic Skills,Basic Skills,Basic Skills,Credit,Credit,...,Transferable,Transferable,Transferable,Transferable,Vocational,Vocational,Vocational,Vocational,Vocational,Basic Skills
1,Gender,Age Group,Ethnicity,Enrollment Count,Retention Count,Success Count,Retention Rate,Success Rate,Enrollment Count,Retention Count,...,Retention Count,Success Count,Retention Rate,Success Rate,Enrollment Count,Retention Count,Success Count,Retention Rate,Success Rate,Enrollment Count
2,Female,1 to 17,African-American,427,364,251,85.25 %,58.78 %,"4,189","3,695",...,"2,849","2,220",88.70 %,69.12 %,751,655,495,87.22 %,65.91 %,364
3,Female,1 to 17,American Indian/Alaskan Native,26,23,15,88.46 %,57.69 %,294,262,...,208,174,89.27 %,74.68 %,29,27,23,93.10 %,79.31 %,32
4,Female,1 to 17,Asian,693,644,560,92.93 %,80.81 %,"9,514","8,862",...,"7,040","6,397",92.96 %,84.47 %,"1,199","1,108",999,92.41 %,83.32 %,563
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,Unknown,Unknown,Asian,2,2,2,100.00 %,100.00 %,11,10,...,5,2,83.33 %,33.33 %,4,4,3,100.00 %,75.00 %,NaN
265,Unknown,Unknown,Hispanic,2,2,0,100.00 %,0.00 %,18,18,...,11,7,100.00 %,63.64 %,10,10,8,100.00 %,80.00 %,1
266,Unknown,Unknown,Pacific Islander,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,Unknown,Unknown,Unknown,5,4,2,80.00 %,40.00 %,48,46,...,32,29,96.97 %,87.88 %,21,20,20,95.24 %,95.24 %,4
268,Unknown,Unknown,White Non-Hispanic,NaN,NaN,NaN,NaN,NaN,4,3,...,1,1,50.00 %,50.00 %,2,2,2,100.00 %,100.00 %,NaN

In [5]:
# age_range = start_cleaning['Unnamed: 3'].unique()
# listed = start_cleaning['Unnamed: 3'] == ('20 to 24' or 'Age Group')
# age_range

In [12]:
#start_cleaning[listed]
#start_cleaning= start_cleaning.rename(columns={'Unnamed: 2': 'Gender', 'Unnamed: 3': 'Age Group', 'Unnamed: 4': 'Ethnicity'})
#start_cleaning.head(15)

In [ ]:
def clean_fall2010_data(database):
    database=database.iloc[:,:29]
    gender_array = database['Gender']
    Age_group = database['Age Group']
    ethnicity = database['Ethnicity']
    basic_enrollment = database['Fall 2010']
    basic_retention = database['Fall 2010.1']
    basic_success = database['Fall 2010.2']
    basic_retrate = database['Fall 2010.3']
    basic_succrate = database['Fall 2010.4']
    combined = {'Gender':gender_array, 'Age Group':Age_group, 'Ethnicity':ethnicity, 'Enrollment Count':basic_enrollment,
               'Retention Count':basic_retention, 'Success Count':basic_success, 'Retention Rate':basic_retrate, 'Success Rate':basic_succrate}
    fall2010 = pd.DataFrame(data=combined)
    fall2010 = fall2010.drop([0,1])
    return fall2010

clean_fall2010_data(start_cleaning)

In [13]:
start_cleaning= start_cleaning.rename(columns={'Unnamed: 2': 'Gender', 'Unnamed: 3': 'Age Group', 'Unnamed: 4': 'Ethnicity'})
winter_2010 = [col for col in start_cleaning.columns if 'Winter 2010' in col]
winter_2010data = start_cleaning[['Gender', 'Age Group', 'Ethnicity'] + winter_2010]

In [44]:
years = range(2010, 2021)
seasons = ['Spring', 'Summer', 'Fall', 'Winter']
terms = []
for y in years:
    for s in seasons:
        terms.append(s + " " + str(y))

In [45]:
all_tables = []
for t in terms:
    term = [col for col in start_cleaning.columns if t in col]
    t = start_cleaning[['Gender', 'Age Group', 'Ethnicity'] + term]
    all_tables.append(t)

In [47]:
all_tables[43]

,Gender,Age Group,Ethnicity,Winter 2020,Winter 2020.1,Winter 2020.2,Winter 2020.3,Winter 2020.4,Winter 2020.5,Winter 2020.6,...,Winter 2020.15,Winter 2020.16,Winter 2020.17,Winter 2020.18,Winter 2020.19,Winter 2020.20,Winter 2020.21,Winter 2020.22,Winter 2020.23,Winter 2020.24
0,NaN,NaN,NaN,Basic Skills,Basic Skills,Basic Skills,Basic Skills,Basic Skills,Credit,Credit,...,Transferable,Transferable,Transferable,Transferable,Transferable,Vocational,Vocational,Vocational,Vocational,Vocational
1,Gender,Age Group,Ethnicity,Enrollment Count,Retention Count,Success Count,Retention Rate,Success Rate,Enrollment Count,Retention Count,...,Enrollment Count,Retention Count,Success Count,Retention Rate,Success Rate,Enrollment Count,Retention Count,Success Count,Retention Rate,Success Rate
2,Female,1 to 17,African-American,NaN,NaN,NaN,NaN,NaN,101,98,...,100,97,90,97.00 %,90.00 %,13,13,13,100.00 %,100.00 %
3,Female,1 to 17,American Indian/Alaskan Native,NaN,NaN,NaN,NaN,NaN,6,6,...,6,6,5,100.00 %,83.33 %,2,2,1,100.00 %,50.00 %
4,Female,1 to 17,Asian,6,6,5,100.00 %,83.33 %,642,627,...,627,612,590,97.61 %,94.10 %,130,127,119,97.69 %,91.54 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,Unknown,Unknown,Asian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,Unknown,Unknown,Hispanic,NaN,NaN,NaN,NaN,NaN,1,1,...,NaN,NaN,NaN,NaN,NaN,1,1,1,100.00 %,100.00 %
266,Unknown,Unknown,Pacific Islander,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,Unknown,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,Unknown,Unknown,White Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN